#%RAML 0.8
title: JRaml test API
version: v1
baseUri: http://jraml.org
protocols: [ HTTP ]
/test:
  post:
    body:
      application/json:
    queryParameters:
      testId:
    responses:
      200:
        body:
          text/plain:
  /{testId}:
      get:
